# --- Configuración del Servidor ---
server.port=${PORT:8080}
logging.level.org.atmosphere = warn
spring.mustache.check-template-location = false

# --- Configuración de Vaadin ---
# Lanza el navegador por defecto al iniciar en modo desarrollo
vaadin.launch-browser=true
# Optimización de paquetes para mejorar el tiempo de respuesta
vaadin.allowed-packages = com.vaadin,org.vaadin,com.flowingcode,com.example.application
spring.jpa.defer-datasource-initialization = true

# --- Conexión a Base de Datos (TiDB Cloud / MySQL) ---
# Se utiliza sslMode para cumplir con los estándares de seguridad de Ingeniería Web
spring.datasource.url=jdbc:mysql://gateway01.us-west-2.prod.aws.tidbcloud.com:4000/test?sslMode=VERIFY_IDENTITY&enabledTLSProtocols=TLSv1.2,TLSv1.3
spring.datasource.username=zCCeUBpw85gG6Fn.root
spring.datasource.password=2or6u30a3C2q7CXH
spring.datasource.driver-class-name=com.mysql.cj.jdbc.Driver

# --- Configuración de Hibernate / JPA ---
spring.jpa.database-platform=org.hibernate.dialect.MySQLDialect
# 'update' asegura que la columna imagen_blob se cree automáticamente al arrancar
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=false
spring.jpa.properties.hibernate.format_sql=true

# --- Ajustes de rendimiento y persistencia en la nube ---
# HikariCP: Gestión del pool de conexiones para evitar timeouts en TiDB
spring.datasource.hikari.max-lifetime=600000
spring.datasource.hikari.connection-timeout=30000
spring.datasource.hikari.maximum-pool-size=10

# --- Gestión de Archivos (Configuración Dinámica de Menús) ---
# Permite subir fotos de productos de hasta 5MB (necesario para el Back-Office)
spring.servlet.multipart.max-file-size=5MB
spring.servlet.multipart.max-request-size=5MB
spring.servlet.multipart.enabled=true