services:
  - type: web
    name: mi-app
    runtime: java
    javaVersion: "17"
    region: frankfurt
    plan: free
    buildCommand: mvn -DskipTests -B clean package -f my-app/pom.xml
    startCommand: java -jar my-app/target/my-app-*.jar
    envVars:
      - key: PORT
        value: "10000"
      - key: JAVA_OPTS
        value: -Xmx512m