services:
  - type: web
    name: mi-app
    runtime: java
    region: frankfurt
    plan: free
    buildCommand: mvn clean package -DskipTests
    startCommand: java -cp target/my-app-*.jar com.example.application.Application
    envVars:
      - key: JAVA_OPTS
        value: -Xmx512m