version: '3.8'

services:
  mysql:
    image: mysql:8.0
    container_name: vaadin_mysql
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: ComidaRapida
      MYSQL_USER: IW
      MYSQL_PASSWORD: LOLALOLITA
    ports:
      - "3306:3306"
    volumes:
      - ./mysql-init:/docker-entrypoint-initdb.d
    networks:
      - vaadin-net

  vaadin_app:
    build: .
    container_name: vaadin_app
    ports:
      - "80:8080"
    depends_on:
      - mysql
    environment:
      SPRING_DATASOURCE_URL: jdbc:mysql://mysql:3306/ComidaRapida
      SPRING_DATASOURCE_USERNAME: IW
      SPRING_DATASOURCE_PASSWORD: LOLALOLITA
    networks:
      - vaadin-net

networks:
  vaadin-net:
